In [2]:
import pandas as pd
data = pd.read_csv("DEMO.csv")
data

,timeStamp,elapsed,label,responseCode,responseMessage,threadName,dataType,success,failureMessage,bytes,sentBytes,grpThreads,allThreads,Latency,IdleTime,Connect
0,1.541090e+12,603,T_01_Home Page,200,OK,Job Round 1-1,text,True,NaN,2674,301,10,30,515,0,130
1,1.541090e+12,369,T_01_Home Page,200,OK,Job Offer 2-9,text,True,NaN,2674,301,10,30,284,0,41
2,1.541090e+12,368,T_01_Home Page,200,OK,Manage Job Adverts 3-10,text,True,NaN,2674,301,10,30,327,0,190
3,1.541090e+12,588,T_01_Home Page,200,OK,Advertise Job 1-7,text,True,NaN,2674,301,10,30,501,0,115
4,1.541090e+12,602,T_01_Home Page,200,OK,Job Offer 2-5,text,True,NaN,2674,301,10,30,515,0,134
5,1.541090e+12,369,T_01_Home Page,200,OK,Manage Job Adverts 3-9,text,True,NaN,2674,301,10,30,285,0,41
6,1.541090e+12,434,T_01_Home Page,200,OK,Job Offer 2-8,text,True,NaN,2674,301,10,30,434,0,86
7,1.541090e+12,401,T_02_Login,200,OK,Advertise Job 1-9,text,True,NaN,2674,301,10,30,314,0,42
8,1.541090e+12,361,T_02_Login,200,OK,Job Offer 2-10,text,True,NaN,2674,301,10,30,317,0,190
9,1.541090e+12,410,T_02_Login,200,OK,Advertise Job 1-10,text,True,NaN,2674,301,10,30,367,0,220
10,1.541090e+12,604,T_02_Login,200,OK,Job Offer 2-2,text,True,NaN,2674,301,10,30,477,0,135
11,1.541090e+12,558,T_02_Login,200,OK,Manage Job Adverts 3-2,text,True,NaN,2674,301,10,30,439,0,130
12,1.541090e+12,493,T_02_Login,200,OK,Advertise Job 1-8,text,True,NaN,2674,301,10,30,405,0,99
13,1.541090e+12,604,T_02_Login,200,OK,Manage Job Adverts 3-3,text,True,NaN,2674,301,10,30,476,0,132
14,1.541090e+12,606,T_02_Login,200,OK,Manage Job Adverts 3-1,text,True,NaN,2674,301,10,30,606,0,134
15,1.541090e+12,559,T_02_Login,200,OK,Job Offer 2-4,text,True,NaN,2674,301,10,30,441,0,131
16,1.541090e+12,559,T_02_Login,200,OK,Advertise Job 1-4,text,True,NaN,2674,301,10,30,474,0,130
17,1.541090e+12,772,T_02_Login,200,OK,Manage Job Adverts 3-4,text,True,NaN,2674,301,10,30,772,0,129
18,1.541090e+12,558,T_03_Logout,200,OK,Advertise Job 1-3,text,True,NaN,2674,301,10,30,439,0,131
19,1.541090e+12,561,T_03_Logout,200,OK,Job Offer 2-6,text,True,NaN,2674,301,10,30,442,0,133
20,1.541090e+12,559,T_03_Logout,200,OK,Manage Job Adverts 3-5,text,True,NaN,2674,301,10,30,559,0,125
21,1.541090e+12,559,T_03_Logout,200,OK,Advertise Job 1-2,text,True,NaN,2674,301,10,30,440,0,131
22,1.541090e+12,559,T_03_Logout,200,OK,Advertise Job 1-6,text,True,NaN,2674,301,10,30,441,0,132
23,1.541090e+12,572,T_03_Logout,200,OK,Manage Job Adverts 3-7,text,True,NaN,2674,301,10,30,445,0,100
24,1.541090e+12,740,T_03_Logout,200,OK,Job Offer 2-7,text,True,NaN,2674,301,10,30,687,0,99
25,1.541090e+12,560,T_03_Logout,200,OK,Advertise Job 1-5,text,True,NaN,2674,301,10,30,441,0,132
26,1.541090e+12,559,T_03_Logout,200,OK,Job Offer 2-1,text,True,NaN,2674,301,10,30,473,0,129
27,1.541090e+12,430,T_03_Logout,200,OK,Manage Job Adverts 3-8,text,True,NaN,2674,301,10,30,344,0,81
28,1.541090e+12,1196,T_03_Logout,200,OK,Manage Job Adverts 3-6,text,True,NaN,2674,301,10,30,1136,0,128
29,1.541090e+12,1197,T_03_Logout,200,OK,Job Offer 2-3,text,True,NaN,2674,301,10,30,1136,0,130

In [7]:
filtered_data = data[data['responseCode'] == 200]
filtered_data

,timeStamp,elapsed,label,responseCode,responseMessage,threadName,dataType,success,failureMessage,bytes,sentBytes,grpThreads,allThreads,Latency,IdleTime,Connect
0,1.541090e+12,603,T_01_Home Page,200,OK,Job Round 1-1,text,True,NaN,2674,301,10,30,515,0,130
1,1.541090e+12,369,T_01_Home Page,200,OK,Job Offer 2-9,text,True,NaN,2674,301,10,30,284,0,41
2,1.541090e+12,368,T_01_Home Page,200,OK,Manage Job Adverts 3-10,text,True,NaN,2674,301,10,30,327,0,190
3,1.541090e+12,588,T_01_Home Page,200,OK,Advertise Job 1-7,text,True,NaN,2674,301,10,30,501,0,115
4,1.541090e+12,602,T_01_Home Page,200,OK,Job Offer 2-5,text,True,NaN,2674,301,10,30,515,0,134
5,1.541090e+12,369,T_01_Home Page,200,OK,Manage Job Adverts 3-9,text,True,NaN,2674,301,10,30,285,0,41
6,1.541090e+12,434,T_01_Home Page,200,OK,Job Offer 2-8,text,True,NaN,2674,301,10,30,434,0,86
7,1.541090e+12,401,T_02_Login,200,OK,Advertise Job 1-9,text,True,NaN,2674,301,10,30,314,0,42
8,1.541090e+12,361,T_02_Login,200,OK,Job Offer 2-10,text,True,NaN,2674,301,10,30,317,0,190
9,1.541090e+12,410,T_02_Login,200,OK,Advertise Job 1-10,text,True,NaN,2674,301,10,30,367,0,220
10,1.541090e+12,604,T_02_Login,200,OK,Job Offer 2-2,text,True,NaN,2674,301,10,30,477,0,135
11,1.541090e+12,558,T_02_Login,200,OK,Manage Job Adverts 3-2,text,True,NaN,2674,301,10,30,439,0,130
12,1.541090e+12,493,T_02_Login,200,OK,Advertise Job 1-8,text,True,NaN,2674,301,10,30,405,0,99
13,1.541090e+12,604,T_02_Login,200,OK,Manage Job Adverts 3-3,text,True,NaN,2674,301,10,30,476,0,132
14,1.541090e+12,606,T_02_Login,200,OK,Manage Job Adverts 3-1,text,True,NaN,2674,301,10,30,606,0,134
15,1.541090e+12,559,T_02_Login,200,OK,Job Offer 2-4,text,True,NaN,2674,301,10,30,441,0,131
16,1.541090e+12,559,T_02_Login,200,OK,Advertise Job 1-4,text,True,NaN,2674,301,10,30,474,0,130
17,1.541090e+12,772,T_02_Login,200,OK,Manage Job Adverts 3-4,text,True,NaN,2674,301,10,30,772,0,129
18,1.541090e+12,558,T_03_Logout,200,OK,Advertise Job 1-3,text,True,NaN,2674,301,10,30,439,0,131
19,1.541090e+12,561,T_03_Logout,200,OK,Job Offer 2-6,text,True,NaN,2674,301,10,30,442,0,133
20,1.541090e+12,559,T_03_Logout,200,OK,Manage Job Adverts 3-5,text,True,NaN,2674,301,10,30,559,0,125
21,1.541090e+12,559,T_03_Logout,200,OK,Advertise Job 1-2,text,True,NaN,2674,301,10,30,440,0,131
22,1.541090e+12,559,T_03_Logout,200,OK,Advertise Job 1-6,text,True,NaN,2674,301,10,30,441,0,132
23,1.541090e+12,572,T_03_Logout,200,OK,Manage Job Adverts 3-7,text,True,NaN,2674,301,10,30,445,0,100
24,1.541090e+12,740,T_03_Logout,200,OK,Job Offer 2-7,text,True,NaN,2674,301,10,30,687,0,99
25,1.541090e+12,560,T_03_Logout,200,OK,Advertise Job 1-5,text,True,NaN,2674,301,10,30,441,0,132
26,1.541090e+12,559,T_03_Logout,200,OK,Job Offer 2-1,text,True,NaN,2674,301,10,30,473,0,129
27,1.541090e+12,430,T_03_Logout,200,OK,Manage Job Adverts 3-8,text,True,NaN,2674,301,10,30,344,0,81
28,1.541090e+12,1196,T_03_Logout,200,OK,Manage Job Adverts 3-6,text,True,NaN,2674,301,10,30,1136,0,128
29,1.541090e+12,1197,T_03_Logout,200,OK,Job Offer 2-3,text,True,NaN,2674,301,10,30,1136,0,130

In [9]:
import numpy as np

result = filtered_data.groupby('label').agg(
    avgLatency=('Latency', 'mean'),
    percentile90=('Latency', lambda x: np.percentile(x, 90))
).reset_index()

In [10]:
result.columns = ['label', 'avgLatency', 'ninperlatency']

result

            label  avgLatency  ninperlatency
0  T_01_Home Page  408.714286          515.0
1      T_02_Login  462.545455          606.0
2     T_03_Logout  581.916667         1091.1

In [11]:
# Save the result to a new CSV file
result.to_csv('output_file.csv', index=False)